{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "name": "config-demo"
  },
  "spec": {
    "containers": [
      {
        "name": "nginx",
        "image": "nginx:1.27",
        "env": [
          {
            "name": "APP_MODE",
            "valueFrom": {
              "configMapKeyRef": {
                "name": "app-config",
                "key": "APP_MODE"
              }
            }
          }
        ]
      }
    ]
  }
}
